-- =========================================================================
-- AI Mentor — daily personal recommendation cache (Pro feature).
-- One row per (user, day). Generated by the `daily-recommendation` Edge
-- Function via Groq and reused for the rest of the calendar day.
-- Run once in the Supabase SQL Editor (idempotent).
-- =========================================================================

-- 1. Subscription tier on the profile (source of truth for AI Mentor gating).
--    The legacy localStorage tier still drives the other paywalls; this column
--    is what the Edge Function and the AI Mentor block check server-side.
alter table public.profiles
  add column if not exists subscription_tier text not null default 'free';

-- Two tiers only: free and pro.
alter table public.profiles drop constraint if exists profiles_subscription_tier_check;
update public.profiles set subscription_tier = 'pro'
  where subscription_tier in ('pro', 'oliy', 'vip');
update public.profiles set subscription_tier = 'free'
  where subscription_tier not in ('free', 'pro');
alter table public.profiles
  add constraint profiles_subscription_tier_check
    check (subscription_tier in ('free', 'pro'));

-- 2. Daily recommendation cache.
create table if not exists public.ai_daily_recommendations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  rec_date date default current_date,
  recommendation text not null,
  action_links jsonb,
  created_at timestamptz default now(),
  unique (user_id, rec_date)
);

alter table public.ai_daily_recommendations enable row level security;

-- Users may read their own recommendations (the Edge Function writes with the
-- service role key, which bypasses RLS).
drop policy if exists "Users read own daily recommendations" on public.ai_daily_recommendations;
create policy "Users read own daily recommendations"
  on public.ai_daily_recommendations for select
  using (auth.uid() = user_id);

create index if not exists idx_ai_daily_rec_user_date
  on public.ai_daily_recommendations(user_id, rec_date);
